### hyprpaper.conf ###

preload = ~/.config/hypr/wallpaper.jpg

wallpaper = eDP-1, ~/.config/hypr/wallpaper.jpg

# Change this when using newest version of hyprpaper

#wallpaper {
#    monitor = *
#    path = ~/.config/hypr/wallpaper.jpg
#    fit_mode = fill
#}
